language: swift
osx_image: xcode10.2

env:
  global:
    - PROJECT='LLAExtensionPack.xcodeproj'
    - IOS_SCHEME='LLAExtensionPack'
    - IOS_DESTINATION='platform=iOS Simulator,name=iPhone X'

before_install:

script:
  - swift --version
  - xcodebuild test -project "$PROJECT" -scheme "$IOS_SCHEME" -sdk iphonesimulator -destination "$IOS_DESTINATION" -configuration Debug

branches:
  only: 
      - master
